# Generated by Django 6.0 on 2026-02-20 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinintake',
            name='protein_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_intake', to='tracker.animalproteinsource'),
        ),
        migrations.AlterField(
            model_name='proteinintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_intake', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyProteinTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_date', models.DateField()),
                ('calculation_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'target_date'), name='unique_target_per_user_per_date')],
            },
        ),
        migrations.CreateModel(
            name='IntakeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField()),
                ('total_protein_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_protein_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'summary_date'), name='unique_summary_per_user_per_date')],
            },
        ),
    ]
